// This file is auto-generated by Lovable. Do not modify it.
// Local fallback: uses Supabase OAuth when @lovable.dev/cloud-auth-js is not installed.

import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

async function signInWithOAuthSupabase(provider: "google" | "apple", opts?: SignInOptions) {
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: provider === "apple" ? "apple" : "google",
    options: {
      redirectTo: opts?.redirect_uri || window.location.origin,
      queryParams: opts?.extraParams,
    },
  });
  if (error) return { error };
  if (data?.url) {
    window.location.href = data.url;
    return { redirected: true };
  }
  return {};
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      try {
        const createLovableAuth = (await import("@lovable.dev/cloud-auth-js")).createLovableAuth;
        const lovableAuth = createLovableAuth();
        const result = await lovableAuth.signInWithOAuth(provider, {
          redirect_uri: opts?.redirect_uri,
          extraParams: opts?.extraParams,
        });
        if (result.redirected) return result;
        if (result.error) return result;
        try {
          await supabase.auth.setSession(result.tokens);
        } catch (e) {
          return { error: e instanceof Error ? e : new Error(String(e)) };
        }
        return result;
      } catch {
        return signInWithOAuthSupabase(provider, opts);
      }
    },
  },
};
